#baseurl:
#url: "https://leesang-pack.github.io"
#
#theme_settings:
#  # Meta
#  title: Leesang's odds and ends
#  avatar: assets/img/blogmark.png
#  favicon: assets/favicon.ico
#  gravatar: # Email MD5 hash
#  description: "leesang blog" # used by search engines
#
#  # Header and footer text
#  header_text: >
#    <p>leesang 잡다구리 연구소</p>
#  header_text_feature_image:
#  footer_text: >
#    Copyright (c) 2021 xzpluszone, www.catlogging.com
#  # Icons
#  rss: true
#  email_address: "xzpluszone@gmail.com" # Full email address, e.g. "sam@example.com"
#  behance:
#  bitbucket:
#  dribbble:
#  facebook:
#  flickr:
#  gitlab:
#  github: "xzpluszone"
#  google_plus:
#  instagram:
#  linkedin:  # Full URL
#  pinterest:
#  reddit:
#  soundcloud:
#  stack_exchange:  # Full URL
#  steam:
#  tumblr:
#  twitter:
#  wordpress:
#  youtube:
#
#  # Scripts
#  google_analytics: G-MV141ZHLS8 # Tracking ID, e.g. "UA-000000-01"
#  disqus_shortname: leesang
#  katex: true # Enable if using math markup
#  search: true # Enable the search feature
#
#  # Localization strings
#  str_follow_on: "Follow on"
#  str_rss_follow: "Follow RSS feed"
#  str_email: "Email"
#  str_next_post: "Next post"
#  str_previous_post: "Previous post"
#  str_next_page: "Next"
#  str_previous_page: "Prev"
#  str_continue_reading: "Continue reading"
#  str_javascript_required_disqus: "Please enable JavaScript to view comments."
#  str_search_no_results: "No results found."
#
#  # Colours, typography and padding
#  # Open the "_sass > base" folder, and open "_variables.scss"
#  google_fonts: "Nanum+Gothic:400,700"
#
#  # Post navigation
#  post_navigation: true
#
#encoding: 'utf-8'
## Configure the plugin here
#category_path: "category" # <- default value
#category_layout: "category.html" # <- default value
#
## PAGINATION
#paginate: 2
#paginate_path: "/page:num"
#
#animation: true
#
## BUILD SETTINGS
#markdown: kramdown
#highlighter: rouge
#sass:
#  sass_dir: _sass
#  style: :compressed
#plugins:
#  - jekyll-paginate
#  - jekyll-category-pages
#gem:
#  - jekyll-sitemap
#  - jekyll-feed
#  - wdm
#theme: jekyll-theme-type
#exclude:
#  - Gemfile
#  - Gemfile.lock
# SITE CONFIGURATION
baseurl: "/type-theme"
url: "https://rohanchandra.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Type Theme
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  header_text_feature_image:
  footer_text: >
    Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>
  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "rohanchandra/type-theme"
  gitter:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock